### ISSUE TITLE
Организовать импорт блоков

### ISSUE THREAD

**Issue by ankokovin** [ankokovin/BlocklyForHouse#2]
На данный момент импорт блоков расположен прямо в [generator.js](https://github.com/ankokovin/BlocklyForHouse/blob/master/blockly-generator/generator/generator.js)

Данный вариант весьма неудобен: придётся копипастить код из определений блоков, что не есть хорошо.

попробывал организовать следующим образом:
```
//door.js
module.exports = (function(Blockly){
...
})()
```

//Аналогично для генератора

//в generator.js
```
var Blockly = require('node-blockly');

require('./blocks/Actuators/door')(Blockly)
...
```

получаю 

> /home/xxxcul/Documents/blocklyforhouse/BlocklyForHouse/blockly-generator/generator/blocks/Actuators/door.js:2
> Blockly.Blocks['door'] = {
>         ^
> 
> TypeError: Cannot read property 'Blocks' of undefined
>     at /home/xxxcul/Documents/blocklyforhouse/BlocklyForHouse/blockly-generator/generator/blocks/Actuators/door.js:2:9
>     at Object.<anonymous> (/home/xxxcul/Documents/blocklyforhouse/BlocklyForHouse/blockly-generator/generator/blocks/Actuators/door.js:52:3)
>     at Module._compile (module.js:652:30)
>     at Object.Module._extensions..js (module.js:663:10)
>     at Module.load (module.js:565:32)
>     at tryModuleLoad (module.js:505:12)
>     at Function.Module._load (module.js:497:3)
>     at Module.require (module.js:596:17)
>     at require (internal/module.js:11:18)
>     at Object.<anonymous> (/home/xxxcul/Documents/blocklyforhouse/BlocklyForHouse/blockly-generator/generator/generator.js:3:1)

**Comment by ankokovin** [comment]
fixed

надо было так:

`module.exports = function (Blockly) { ... }`

[коммит](https://github.com/ankokovin/BlocklyForHouse/commit/8f4290a65ea33e00edb9db79c6d3ea2aefd23fa8)
